name: CDK CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Required to use the AWS CLI
permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Install all dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - run: npm ci

      # Test the app
      - run: npm test

      # Scan for vulnerabilities
      - run: npm run cdk synth

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push'

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Install all dependencies
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - run: npm ci

      # Build the app
      - run: npm run cdk bootstrap
      - run: npm run cdk synth

      # Deploy to dev/QA/prod
      - run: npm run cdk deploy --require-approval never
      - run: npm run cdk destroy # don't persist deployements for demo purposes
